<a href="https://colab.research.google.com/github/pahrul23/pahrul-skripsi/blob/main/SKRIPSI_LIBRARY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LOAD** **DAN** **PREPROCESSING** **DATA**

In [ ]:
!pip install nltk
!pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 KB 8.6 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df_dataTraining = pd.read_csv('drive/MyDrive/Wira/labelV1.csv', encoding="ISO-8859-1")

In [ ]:
df_dataTraining

label                                           filtered  \
0        1.0                                             mantap   
1       -1.0  kenapa saya ditagih hutang kan saya di tolak p...   
2        1.0                                       sangat bagus   
3        1.0                                              bagus   
4        1.0  ini pengajuan pertama moga di acc krn lg butuh...   
...      ...                                                ...   
17636   -1.0                                   ada kami ngentod   
17637   -1.0  waktu jatuh tempo masih hari tapi panggilan ma...   
17638   -1.0  pelayanan dan csnya buruk blum waktunya byar s...   
17639   -1.0  aplikasi busuk baru daftar udah di tolak penga...   
17640   -1.0                       hadeh apk apaan sih ga jelas   

                                                 cleaned  \
0                                                 mantap   
1      kenapa saya tagih hutang saya tolak pinjam man...   
2                                           sangat bagus   
3                                                  bagus   
4      aju pertama moga acc lg butuh dana kembang war...   
...                                                  ...   
17636                                   ada kami ngentod   
17637  jatuh tempo masih hari tapi panggil masuk tagi...   
17638  layan csnya buruk blum waktu byar sdah tagih k...   
17639  aplikasi busuk baru daftar udah tolak aju pinj...   
17640                             hadeh apk apa ga jelas   

                                          content_tokens  \
0                                             ['mantap']   
1      ['kenapa', 'saya', 'tagih', 'hutang', 'saya', ...   
2                                    ['sangat', 'bagus']   
3                                              ['bagus']   
4      ['aju', 'pertama', 'moga', 'acc', 'lg', 'butuh...   
...                                                  ...   
17636                         ['ada', 'kami', 'ngentod']   
17637  ['jatuh', 'tempo', 'masih', 'hari', 'tapi', 'p...   
17638  ['layan', 'csnya', 'buruk', 'blum', 'waktu', '...   
17639  ['aplikasi', 'busuk', 'baru', 'daftar', 'udah'...   
17640             ['hadeh', 'apk', 'apa', 'ga', 'jelas']   

                                             normalisasi  
0                                             ['mantap']  
1      ['kenapa', 'aku', 'tagih', 'hutang', 'aku', 't...  
2                                    ['sangat', 'bagus']  
3                                              ['bagus']  
4      ['aju', 'pertama', 'semoga', 'terima', 'lagi',...  
...                                                  ...  
17636                         ['ada', 'kami', 'ngentod']  
17637  ['jatuh', 'tempo', 'masih', 'hari', 'tapi', 'p...  
17638  ['layan', 'csnya', 'buruk', 'blum', 'waktu', '...  
17639  ['aplikasi', 'busuk', 'baru', 'daftar', 'sudah...  
17640      ['aduh', 'aplikasi', 'apa', 'tidak', 'jelas']  

[17641 rows x 5 columns]

In [ ]:
print(df_dataTraining['label'].value_counts())
# print(df_dataTraining.value_counts())

 1.0    7783
-1.0    7736
 0.0    2121
Name: label, dtype: int64


In [ ]:
df_dataTraining['label'] = df_dataTraining['label'].replace([1], '2')
df_dataTraining['label'] = df_dataTraining['label'].replace([-1], '1')
df_dataTraining['label'] = df_dataTraining['label'].replace([0], '0')

In [ ]:
df_dataTraining['label'].value_counts()

2    7783
1    7736
0    2121
Name: label, dtype: int64

In [ ]:
#2 Untuk Positif
#1 Untuk Negatif
#0 Untuk Netral

In [ ]:
# import seaborn as sns
# sns.countplot(df_dataTraining['label'])

In [ ]:
df_dataTraining

label                                           filtered  \
0         2                                             mantap   
1         1  kenapa saya ditagih hutang kan saya di tolak p...   
2         2                                       sangat bagus   
3         2                                              bagus   
4         2  ini pengajuan pertama moga di acc krn lg butuh...   
...     ...                                                ...   
17636     1                                   ada kami ngentod   
17637     1  waktu jatuh tempo masih hari tapi panggilan ma...   
17638     1  pelayanan dan csnya buruk blum waktunya byar s...   
17639     1  aplikasi busuk baru daftar udah di tolak penga...   
17640     1                       hadeh apk apaan sih ga jelas   

                                                 cleaned  \
0                                                 mantap   
1      kenapa saya tagih hutang saya tolak pinjam man...   
2                                           sangat bagus   
3                                                  bagus   
4      aju pertama moga acc lg butuh dana kembang war...   
...                                                  ...   
17636                                   ada kami ngentod   
17637  jatuh tempo masih hari tapi panggil masuk tagi...   
17638  layan csnya buruk blum waktu byar sdah tagih k...   
17639  aplikasi busuk baru daftar udah tolak aju pinj...   
17640                             hadeh apk apa ga jelas   

                                          content_tokens  \
0                                             ['mantap']   
1      ['kenapa', 'saya', 'tagih', 'hutang', 'saya', ...   
2                                    ['sangat', 'bagus']   
3                                              ['bagus']   
4      ['aju', 'pertama', 'moga', 'acc', 'lg', 'butuh...   
...                                                  ...   
17636                         ['ada', 'kami', 'ngentod']   
17637  ['jatuh', 'tempo', 'masih', 'hari', 'tapi', 'p...   
17638  ['layan', 'csnya', 'buruk', 'blum', 'waktu', '...   
17639  ['aplikasi', 'busuk', 'baru', 'daftar', 'udah'...   
17640             ['hadeh', 'apk', 'apa', 'ga', 'jelas']   

                                             normalisasi  
0                                             ['mantap']  
1      ['kenapa', 'aku', 'tagih', 'hutang', 'aku', 't...  
2                                    ['sangat', 'bagus']  
3                                              ['bagus']  
4      ['aju', 'pertama', 'semoga', 'terima', 'lagi',...  
...                                                  ...  
17636                         ['ada', 'kami', 'ngentod']  
17637  ['jatuh', 'tempo', 'masih', 'hari', 'tapi', 'p...  
17638  ['layan', 'csnya', 'buruk', 'blum', 'waktu', '...  
17639  ['aplikasi', 'busuk', 'baru', 'daftar', 'sudah...  
17640      ['aduh', 'aplikasi', 'apa', 'tidak', 'jelas']  

[17641 rows x 5 columns]

In [ ]:
df_dataTraining['label'].dtypes

dtype('O')

In [ ]:
df_dataTraining['label'] = pd.to_numeric(df_dataTraining['label'])

In [ ]:
df_dataTraining['label'].dtypes

dtype('float64')

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
stop=set(stopwords.words("indonesian"))
stop_bow = set(stopwords.words("indonesian"))
stop_bow.discard("tidak")
factory = StemmerFactory()
stemmer = factory.create_stemmer()

text=df_dataTraining["normalisasi"]
cleaned_text_bow=[]
cleaned_text=[]
for line in text:
    tags = re.compile("^@[a-zA-Z_]*")
    line = re.sub(tags," ",str(line))
    hashtags = re.compile("#|\*")
    extraCharacters = re.compile("[^a-zA-Z]")
    line = re.sub(extraCharacters," ",str(line))

    filtered_words=[]
    filtered_words_bow=""
    for word in line.split():
        word=word.lower()
        if(word not in stop):
            word = stemmer.stem(word)
            filtered_words.append(word)
        if(word not in stop_bow):
            word = stemmer.stem(word)
            filtered_words_bow+=" "+word
    cleaned_text.append(filtered_words)
    cleaned_text_bow.append(filtered_words_bow)
            
data_bow = pd.DataFrame(data=cleaned_text_bow,columns=["Stemming"])
data_bow["label"] = df_dataTraining["label"]
df_dataTraining["Stemming"]=cleaned_text
print(df_dataTraining.head(10))
print()
print(data_bow.head(10))
print()

   label                                           filtered  \
0    2.0                                             mantap   
1    1.0  kenapa saya ditagih hutang kan saya di tolak p...   
2    2.0                                       sangat bagus   
3    2.0                                              bagus   
4    2.0  ini pengajuan pertama moga di acc krn lg butuh...   
5    2.0                                    sangat membantu   
6    0.0  menurut saya bagus cuma bunga creditnya agak b...   
7    0.0                                                NaN   
8    2.0  yth bapak ibu saya yang bernama meminta tolong...   
9    0.0                                 semoga bisa di acc   

                                             cleaned  \
0                                             mantap   
1  kenapa saya tagih hutang saya tolak pinjam man...   
2                                       sangat bagus   
3                                              bagus   
4  aju pertama moga acc lg

In [ ]:
# df_dataTraining.to_csv(r'drive/MyDrive/Wira/Word2Vec.csv', index = False, header = True,index_label=None)

**Word Embadding (Word2vec)**

---



In [ ]:
import gensim
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler

In [ ]:
# Train on text data
list_of_sent = df_dataTraining["Stemming"]
w2v_model = gensim.models.Word2Vec(list_of_sent, min_count=4, vector_size=200, workers=4, negative=10, seed=34) #vector_size = ukuran vector yg diinginkan, default cbow
w2v_words = list(w2v_model.wv.index_to_key) #corpus/vocab ambil dr kata yg ada di data train 

# """
# Pertama, kode mengambil kolom "Stemming" dari dataframe df_dataTraining, yang berisi daftar kalimat yang telah diproses menjadi kata-kata dasar (stemmed).
# Kemudian, model Word2Vec diinisialisasi dengan parameter min_count=4, artinya hanya kata-kata yang muncul sebanyak 4 kali atau lebih yang akan dimasukkan ke dalam kamus, size=200, 
# artinya vektor embedding yang dibuat memiliki panjang 200, workers=4, artinya pelatihan dilakukan dengan 4 thread, negative=10, artinya jumlah kata negatif yang diambil saat pelatihan adalah 10, dan seed=34, 
# artinya seed yang digunakan untuk inisialisasi model. Selanjutnya, kamus kata-kata yang ada di dalam model diambil dan disimpan dalam variabel w2v_words. 
# Kamus ini nantinya akan digunakan untuk membangun vektor representasi untuk setiap kata pada data uji dan latih.
# """

In [ ]:
# menyimpan model
w2v_model.save("w2v_model.model")

In [ ]:
df_dataTraining["Stemming"]

0                                                 [mantap]
1        [tagih, hutang, tolak, pinjam, bawa, hukum, to...
2                                                  [bagus]
3                                                  [bagus]
4        [aju, moga, terima, butuh, dana, kembang, waru...
                               ...                        
17636                                            [ngentod]
17637    [jatuh, tempo, panggil, masuk, tagih, sampi, k...
17638    [layan, csnya, buruk, blum, byar, sdah, tagih,...
17639    [aplikasi, busuk, daftar, tolak, aju, pinjam, ...
17640                                     [aduh, aplikasi]
Name: Stemming, Length: 17641, dtype: object

In [ ]:
len(w2v_words)

1764

In [ ]:
#Vectorize train text data
listof_sent_vec=[]
for sent in tqdm(list_of_sent): 
    sent_vec = np.zeros(200) 
    cnt_words =0; 
    for word in sent: 
        if word in w2v_words:
            vec = w2v_model.wv[word]
            sent_vec += vec
            cnt_words += 1
    if cnt_words != 0:
        sent_vec /= cnt_words
    listof_sent_vec.append(sent_vec)
    
Label = df_dataTraining["label"]
list_col=tuple(range(200))
Scaler = StandardScaler()
train_vec = Scaler.fit_transform(listof_sent_vec)
W2v_df_dataTraining=pd.DataFrame(data=train_vec, columns=list_col)
W2v_df_dataTraining["label"] = Label

print(W2v_df_dataTraining.head(10))
print(W2v_df_dataTraining.shape)


# """
# Proses vektorisasi dilakukan pada data training dengan mengubah setiap kalimat menjadi vektor berukuran 200 dimensi. Pada bagian pertama, list_of_sent berisi daftar kalimat yang sudah di-stemming dari data training. 
# Kemudian, model word2vec diinisialisasi dengan menggunakan parameter sebagai berikut:

# min_count=4: kata yang muncul kurang dari 4 kali diabaikan dalam pembuatan vektor
# size=200: ukuran vektor yang diinginkan
# workers=4: jumlah thread yang digunakan untuk training
# negative=10: jumlah kata yang dipilih sebagai negatif sampling
# seed=34: seed untuk randomization

# Setelah model word2vec dilatih, w2v_words menyimpan kumpulan kata-kata yang muncul di data training. Kemudian dilakukan iterasi pada setiap kalimat di list_of_sent. Untuk setiap kata di kalimat tersebut, 
# dicari vektor word2vec yang sesuai. Jika kata tidak ditemukan dalam w2v_words, maka kata tersebut diabaikan. Jika kata ditemukan, maka vektor word2vec-nya dijumlahkan pada sent_vec dan cnt_words ditambah 1. 
# Setelah iterasi selesai, sent_vec dibagi dengan cnt_words untuk mendapatkan rata-rata vektor kalimat tersebut. Selanjutnya, sent_vec dimasukkan ke dalam listof_sent_vec.
# Terakhir, hasil vektorisasi tersebut disimpan ke dalam dataframe W2v_df_dataTraining. Kolom label menyimpan label dari setiap kalimat, sedangkan kolom-kolom lainnya menyimpan nilai vektor. 
# Sebelum disimpan, dilakukan normalisasi pada vektor menggunakan StandardScaler dari sklearn.preprocessing.


# """

100%|██████████| 17641/17641 [00:01<00:00, 16226.08it/s]


          0         1         2         3         4         5         6  \
0  0.342396 -0.389589  0.470020 -0.863059 -0.985634 -0.299488 -0.239083   
1 -1.327985 -0.175099 -1.487017 -0.483551 -0.340173 -0.560382 -1.559313   
2  0.216104 -0.426337  0.582890 -0.198371 -0.559057 -0.227799 -0.027062   
3  0.216104 -0.426337  0.582890 -0.198371 -0.559057 -0.227799 -0.027062   
4  0.137395  0.727792 -0.283191 -0.164068  0.466066 -0.258626  0.725946   
5  0.124306  0.567513 -0.208390 -1.368548 -0.907389 -1.180292 -0.573782   
6  1.169800 -1.495950  1.767413  0.608364 -0.865902  0.993045  0.370060   
7  2.081497  2.344176  0.114518  1.269672  3.229348  2.143041  2.353612   
8 -2.166318  0.617924 -2.950089 -1.889101 -0.812361 -1.379588 -1.822651   
9 -0.925756  1.558034 -1.198595 -1.685528 -0.469628 -1.534950  0.785178   

          7         8         9  ...       191       192       193       194  \
0 -1.416482  0.051724 -1.569476  ... -0.025088  1.168700  1.250729  0.945818   
1  0.680134  1

# **LANGSUNG LOAD DATA HASIL PREPROCESSING**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
W2v_df_dataTraining = pd.read_csv('drive/MyDrive/Wira/Word2Vec.csv', encoding="ISO-8859-1")

In [4]:
W2v_df_dataTraining

0         1         2         3         4         5         6  \
0      0.589647 -0.032969  1.577858 -0.261099 -0.816928  1.169729 -0.045591   
1      0.169849 -0.948463 -1.936053  0.370609 -0.218172  0.135423  1.503564   
2      0.049207 -0.055259  1.162899  0.103344 -0.585705  0.272081 -0.464852   
3      0.049207 -0.055259  1.162899  0.103344 -0.585705  0.272081 -0.464852   
4      0.284075  0.624841  0.282875 -0.772059  0.575722  0.398152 -0.181389   
...         ...       ...       ...       ...       ...       ...       ...   
17635  1.421210  3.128096  0.114922 -2.611097  3.436417 -1.410561 -0.976095   
17636 -2.929913 -1.509963 -1.346306  1.939351 -0.224151 -1.337806 -1.937517   
17637 -0.958356 -0.204796 -0.415086  0.642472  0.206285 -0.827741 -0.794551   
17638  0.524655 -1.013381 -2.308306  0.158416 -0.202552  0.506964  2.059501   
17639  0.759523  0.627998 -0.269104 -0.375059  0.683213 -0.262889  0.564891   

              7         8         9  ...       191       192       193  \
0      0.105004 -1.654137  0.374675  ... -1.184555 -0.482295 -1.474492   
1     -0.821239  0.996892 -1.880665  ...  0.341622 -0.482107  0.355359   
2      0.505787 -0.900250  0.626195  ... -0.431760  0.167611 -0.705386   
3      0.505787 -0.900250  0.626195  ... -0.431760  0.167611 -0.705386   
4     -0.392350 -0.220285  0.273051  ... -0.438284 -0.567406  0.195598   
...         ...       ...       ...  ...       ...       ...       ...   
17635 -1.382296  0.751334  1.908477  ...  0.470704  0.420560  1.974974   
17636  2.330764  2.523358  0.509626  ...  2.653045  2.623997  2.299301   
17637  0.744620  0.938180  0.443751  ...  0.945847  0.975964  0.969092   
17638 -1.338397  1.018989 -2.423215  ...  0.114741 -0.998798  0.224538   
17639 -0.862586  0.073697 -0.056642  ...  0.178904  0.041351  0.028916   

            194       195       196       197       198       199  label  
0      1.697958  0.375751  0.555185  0.375916  0.981808 -1.704464      2  
1     -0.834764  0.591695 -1.615025 -1.132158  0.398693  0.635384      1  
2      1.139312  0.352743  0.562127  0.703678  0.562917 -0.809697      2  
3      1.139312  0.352743  0.562127  0.703678  0.562917 -0.809697      2  
4     -0.231363 -0.827963  0.422755 -0.221953 -0.709832 -0.015067      2  
...         ...       ...       ...       ...       ...       ...    ...  
17635 -2.383461 -3.285148  2.407402 -1.522504 -3.361125  1.637426      1  
17636 -1.443935  1.025284 -1.089208  2.151263 -0.149006  2.373927      1  
17637 -0.477760  0.025019 -0.080705  0.633886 -0.314003  0.856739      1  
17638 -0.922002  0.580955 -1.963623 -1.629168  0.435039  0.590974      1  
17639 -0.403917 -0.590287  0.353710 -0.896975 -0.327168  0.057265      1  

[17640 rows x 201 columns]

In [5]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(W2v_df_dataTraining)
W2v_df_dataTraining

<ipython-input-5-ef2e4129967e>:4: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)


0         1         2         3         4         5         6  \
0      0.589647 -0.032969  1.577858 -0.261099 -0.816928  1.169729 -0.045591   
1      0.169849 -0.948463 -1.936053  0.370609 -0.218172  0.135423  1.503564   
2      0.049207 -0.055259  1.162899  0.103344 -0.585705  0.272081 -0.464852   
3      0.049207 -0.055259  1.162899  0.103344 -0.585705  0.272081 -0.464852   
4      0.284075  0.624841  0.282875 -0.772059  0.575722  0.398152 -0.181389   
...         ...       ...       ...       ...       ...       ...       ...   
17635  1.421210  3.128096  0.114922 -2.611097  3.436417 -1.410561 -0.976095   
17636 -2.929913 -1.509963 -1.346306  1.939351 -0.224151 -1.337806 -1.937517   
17637 -0.958356 -0.204796 -0.415086  0.642472  0.206285 -0.827741 -0.794551   
17638  0.524655 -1.013381 -2.308306  0.158416 -0.202552  0.506964  2.059501   
17639  0.759523  0.627998 -0.269104 -0.375059  0.683213 -0.262889  0.564891   

              7         8         9  ...       191       192       193  \
0      0.105004 -1.654137  0.374675  ... -1.184555 -0.482295 -1.474492   
1     -0.821239  0.996892 -1.880665  ...  0.341622 -0.482107  0.355359   
2      0.505787 -0.900250  0.626195  ... -0.431760  0.167611 -0.705386   
3      0.505787 -0.900250  0.626195  ... -0.431760  0.167611 -0.705386   
4     -0.392350 -0.220285  0.273051  ... -0.438284 -0.567406  0.195598   
...         ...       ...       ...  ...       ...       ...       ...   
17635 -1.382296  0.751334  1.908477  ...  0.470704  0.420560  1.974974   
17636  2.330764  2.523358  0.509626  ...  2.653045  2.623997  2.299301   
17637  0.744620  0.938180  0.443751  ...  0.945847  0.975964  0.969092   
17638 -1.338397  1.018989 -2.423215  ...  0.114741 -0.998798  0.224538   
17639 -0.862586  0.073697 -0.056642  ...  0.178904  0.041351  0.028916   

            194       195       196       197       198       199  label  
0      1.697958  0.375751  0.555185  0.375916  0.981808 -1.704464      2  
1     -0.834764  0.591695 -1.615025 -1.132158  0.398693  0.635384      1  
2      1.139312  0.352743  0.562127  0.703678  0.562917 -0.809697      2  
3      1.139312  0.352743  0.562127  0.703678  0.562917 -0.809697      2  
4     -0.231363 -0.827963  0.422755 -0.221953 -0.709832 -0.015067      2  
...         ...       ...       ...       ...       ...       ...    ...  
17635 -2.383461 -3.285148  2.407402 -1.522504 -3.361125  1.637426      1  
17636 -1.443935  1.025284 -1.089208  2.151263 -0.149006  2.373927      1  
17637 -0.477760  0.025019 -0.080705  0.633886 -0.314003  0.856739      1  
17638 -0.922002  0.580955 -1.963623 -1.629168  0.435039  0.590974      1  
17639 -0.403917 -0.590287  0.353710 -0.896975 -0.327168  0.057265      1  

[17640 rows x 201 columns]

In [6]:
X = W2v_df_dataTraining.drop("label",axis=1).to_numpy()
X

array([[ 0.5896474 , -0.0329686 ,  1.57785791, ...,  0.37591602,
         0.98180843, -1.70446447],
       [ 0.16984885, -0.94846334, -1.93605267, ..., -1.13215766,
         0.39869305,  0.635384  ],
       [ 0.04920737, -0.05525941,  1.16289923, ...,  0.70367819,
         0.56291684, -0.80969728],
       ...,
       [-0.95835596, -0.2047959 , -0.41508558, ...,  0.63388551,
        -0.31400326,  0.85673897],
       [ 0.5246552 , -1.01338077, -2.30830572, ..., -1.62916827,
         0.43503892,  0.59097428],
       [ 0.75952328,  0.62799785, -0.26910375, ..., -0.89697514,
        -0.32716766,  0.057265  ]])

In [7]:
y = W2v_df_dataTraining['label'].to_numpy()
X = W2v_df_dataTraining.drop("label",axis=1).to_numpy()

In [8]:
W2v_df_dataTraining['label'] = pd.to_numeric(W2v_df_dataTraining['label'])

In [9]:
y = W2v_df_dataTraining["label"].to_numpy()
y[0:5]

array([2, 1, 2, 2, 2])

In [10]:
# W2v_df_dataTraining.to_csv(r'drive/MyDrive/Wira/Word2Vec.csv', index = False, header = True,index_label=None)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2, stratify=y, random_state=30)

In [12]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(14112, 200)
(14112,)
(3528, 200)
(3528,)


# **RANDOM** **FOREST**

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [21]:
# Train Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predict sentiment for test data
y_pred = clf.predict(X_test)

In [22]:
# Evaluate accuracy of classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8078231292517006
Classification Report:
              precision    recall  f1-score   support

           0       0.59      0.31      0.40       424
           1       0.84      0.88      0.86      1547
           2       0.81      0.87      0.84      1557

    accuracy                           0.81      3528
   macro avg       0.74      0.69      0.70      3528
weighted avg       0.79      0.81      0.80      3528

Confusion Matrix:
[[ 130  114  180]
 [  38 1368  141]
 [  53  152 1352]]


# **XGBOOST**

In [23]:
import xgboost as xgb

In [24]:
# Train XGBoost classifier
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
param = {
    'max_depth': 6,
    'eta': 0.3,
    'objective': 'multi:softmax',
    'num_class': len(set(y_train)) + 1
}
num_round = 100
bst = xgb.train(param, dtrain, num_round)

# Predict sentiment for test data
y_pred = bst.predict(dtest)

In [26]:
# Evaluate accuracy of classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8038548752834467
Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.31      0.40       424
           1       0.84      0.88      0.86      1547
           2       0.80      0.87      0.84      1557

    accuracy                           0.80      3528
   macro avg       0.74      0.68      0.70      3528
weighted avg       0.79      0.80      0.79      3528

Confusion Matrix:
[[ 130  119  175]
 [  40 1354  153]
 [  60  145 1352]]


# **SVM**

In [13]:
from sklearn import svm
from sklearn.metrics import accuracy_score

In [14]:
# Train SVM classifier
clf = svm.SVC(kernel='linear', C=1, decision_function_shape='ovr')
clf.fit(X_train, y_train)

# Predict sentiment for test data
y_pred = clf.predict(X_test)

In [15]:
y_pred

array([2, 2, 2, ..., 2, 1, 2])

In [16]:
# Evaluate accuracy of classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8234126984126984


In [19]:
from sklearn.metrics import classification_report, confusion_matrix

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.29      0.41       424
           1       0.85      0.90      0.87      1547
           2       0.81      0.90      0.85      1557

    accuracy                           0.82      3528
   macro avg       0.78      0.69      0.71      3528
weighted avg       0.81      0.82      0.81      3528

Confusion Matrix:
[[ 122  116  186]
 [  22 1388  137]
 [  32  130 1395]]
